[package]
name = "aoc2020_13"
version = "0.1.0"
authors = ["Pavel Tumik <pavel.tumik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
